# Generated by Django 6.0.6 on 2026-07-19 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='نام گیرنده')),
                ('phone_number', models.CharField(help_text='مثال: 09123456789', max_length=15, verbose_name='شماره تماس')),
                ('postal_code', models.CharField(help_text='کد پستی ۱۰ رقمی', max_length=10, verbose_name='کد پستی')),
                ('province', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('address_line', models.CharField(help_text='آدرس دقیق پستی شامل نام کوچه، پلاک و واحد', max_length=255, verbose_name='آدرس پستی')),
                ('is_default', models.BooleanField(default=False, help_text='این آدرس به عنوان پیش\u200cفرض برای سفارش\u200cها استفاده شود.', verbose_name='آدرس پیش\u200cفرض')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
                'ordering': ['-is_default', '-updated'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='accounts_ad_user_id_c8244c_idx'), models.Index(fields=['-updated'], name='accounts_ad_updated_a2bcb4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_user')],
            },
        ),
    ]
