# Generated by Django 6.0.6 on 2026-07-30 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_accountAddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='شماره موبایل')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='کد تایید')),
                ('otp_created_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ایجاد کد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل\u200cها',
                'indexes': [models.Index(fields=['phone_number'], name='accounts_pr_phone_n_c27a97_idx')],
            },
        ),
    ]
