"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import secrets

from dotenv import load_dotenv
from django.utils.csp import CSP


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local development values when a .env file exists.
# Deployment environments should provide configuration through environment
# variables directly.
load_dotenv(BASE_DIR / ".env")


# -------------------------------------------------------------------------
# Environment helpers
# -------------------------------------------------------------------------

_TRUE_VALUES = {"1", "true", "yes", "on"}
_FALSE_VALUES = {"0", "false", "no", "off"}


def _env_bool(name: str, *, default: bool) -> bool:
    raw_value = os.getenv(name)
    if raw_value is None:
        return default

    value = raw_value.strip().lower()
    if value in _TRUE_VALUES:
        return True
    if value in _FALSE_VALUES:
        return False

    raise RuntimeError(
        f"{name} must be one of: "
        "1, 0, true, false, yes, no, on, off."
    )


def _env_csv(name: str) -> list[str]:
    return [
        value.strip()
        for value in os.getenv(name, "").split(",")
        if value.strip()
    ]


def _required_env(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        raise RuntimeError(f"{name} must be set.")
    return value


# -------------------------------------------------------------------------
# Security
# -------------------------------------------------------------------------

DEBUG = _env_bool("DJANGO_DEBUG", default=True)

# SECRET_KEY is always read from the environment. In development only, when
# a key was not supplied, generate an ephemeral key so no reusable secret is
# embedded in source control. Production must provide a persistent key.
SECRET_KEY = os.getenv("SECRET_KEY", "").strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = f"django-insecure-{secrets.token_urlsafe(64)}"
    else:
        raise RuntimeError("SECRET_KEY must be set when DJANGO_DEBUG=0.")


# Development hosts: local access plus rotating LocalTunnel subdomains.
if DEBUG:
    configured_hosts = _env_csv("ALLOWED_HOSTS")
    ALLOWED_HOSTS = configured_hosts or [
        "127.0.0.1",
        "localhost",
        ".loca.lt",
    ]
else:
    ALLOWED_HOSTS = _env_csv("ALLOWED_HOSTS")
    if not ALLOWED_HOSTS:
        raise RuntimeError("ALLOWED_HOSTS must be set when DJANGO_DEBUG=0.")


# LocalTunnel is development-only. Production must use explicit origins.
CSRF_TRUSTED_ORIGINS = _env_csv("CSRF_TRUSTED_ORIGINS")
if DEBUG and "https://*.loca.lt" not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append("https://*.loca.lt")


# -------------------------------------------------------------------------
# Session / CSRF cookie security
# -------------------------------------------------------------------------
# HTTPS-only cookies are required in production. Development remains usable
# over local HTTP. Session cookies are HttpOnly; the CSRF cookie remains
# JavaScript-readable because the frontend reads csrftoken for AJAX requests.
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"


# -------------------------------------------------------------------------
# Content Security Policy (Report-Only)
# -------------------------------------------------------------------------
# Phase 3.7.4 deliberately starts in Report-Only mode. The current frontend
# contains inline JavaScript/event handlers and approved third-party assets;
# this policy records browser violations without blocking site behavior.
SECURE_CSP_REPORT_ONLY = {
    "default-src": [CSP.SELF],
    "script-src": [
        CSP.SELF,
        "https://cdn.tailwindcss.com",
        "https://cdnjs.cloudflare.com",
        "https://code.jquery.com",
        "https://cdn.jsdelivr.net",
    ],
    "style-src": [
        CSP.SELF,
        "https://cdnjs.cloudflare.com",
        "https://cdn.jsdelivr.net",
    ],
    "font-src": [CSP.SELF, "https://cdnjs.cloudflare.com"],
    "img-src": [CSP.SELF, "data:"],
    "connect-src": [CSP.SELF],
    "form-action": [CSP.SELF],
    "object-src": [CSP.NONE],
    "base-uri": [CSP.SELF],
    "frame-ancestors": [CSP.NONE],
}

# Enforcement is intentionally deferred until real browser violations have
# been audited and the existing inline frontend has been migrated safely.
SECURE_CSP = {}


# -------------------------------------------------------------------------
# Application definition
# -------------------------------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    # MyApp
    "catalog",
    "cart",
    "accounts",
    "orders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.csp.ContentSecurityPolicyMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cart.context_processors.cart_summary",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# -------------------------------------------------------------------------
# Database
# NOTE: Database hardening/migration to production DB belongs to phase 3.7.6.
# -------------------------------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# -------------------------------------------------------------------------
# Password validation
# -------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "catalog:home"
LOGOUT_REDIRECT_URL = "catalog:home"


# -------------------------------------------------------------------------
# Internationalization
# -------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# -------------------------------------------------------------------------
# Static files (CSS, JavaScript, Images)
# -------------------------------------------------------------------------

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# -------------------------------------------------------------------------
# SMS.ir Configuration
# -------------------------------------------------------------------------

SMSIR_CONFIG = {
    "API_KEY": os.getenv("SMSIR_API_KEY", "").strip(),
    "TEMPLATE_ID": int(os.getenv("SMSIR_TEMPLATE_ID", "358253") or 358253),
}

if not DEBUG and not SMSIR_CONFIG["API_KEY"]:
    raise RuntimeError("SMSIR_API_KEY must be set when DJANGO_DEBUG=0.")


# -------------------------------------------------------------------------
# Payment / gateway configuration
# -------------------------------------------------------------------------

PAYMENT_CALLBACK_SECRET = os.getenv("PAYMENT_CALLBACK_SECRET", "").strip()
if not PAYMENT_CALLBACK_SECRET:
    if DEBUG:
        PAYMENT_CALLBACK_SECRET = SECRET_KEY
    else:
        raise RuntimeError(
            "PAYMENT_CALLBACK_SECRET must be set when DJANGO_DEBUG=0."
        )


PAYMENT_DEFAULT_GATEWAY = os.getenv("PAYMENT_DEFAULT_GATEWAY", "").strip()
if not PAYMENT_DEFAULT_GATEWAY:
    if DEBUG:
        PAYMENT_DEFAULT_GATEWAY = "mock_gateway"
    else:
        raise RuntimeError(
            "PAYMENT_DEFAULT_GATEWAY must be set when DJANGO_DEBUG=0."
        )


# -------------------------------------------------------------------------
# ZarinPal
# -------------------------------------------------------------------------
# Sandbox defaults are development-only. When ZarinPal is the selected
# production gateway, merchant/callback/endpoints must be explicit and the
# production endpoints may not point to the sandbox host.
ZARINPAL_MERCHANT_ID = os.getenv("ZARINPAL_MERCHANT_ID", "").strip()
ZARINPAL_CALLBACK_URL = os.getenv("ZARINPAL_CALLBACK_URL", "").strip()
ZARINPAL_CURRENCY = (
    os.getenv("ZARINPAL_CURRENCY", "IRT").strip().upper() or "IRT"
)
ZARINPAL_HTTP_TIMEOUT = os.getenv("ZARINPAL_HTTP_TIMEOUT", "15").strip() or "15"

if DEBUG:
    ZARINPAL_REQUEST_URL = (
        os.getenv(
            "ZARINPAL_REQUEST_URL",
            "https://sandbox.zarinpal.com/pg/v4/payment/request.json",
        )
        .strip()
    )
    ZARINPAL_VERIFY_URL = (
        os.getenv(
            "ZARINPAL_VERIFY_URL",
            "https://sandbox.zarinpal.com/pg/v4/payment/verify.json",
        )
        .strip()
    )
    ZARINPAL_STARTPAY_URL = (
        os.getenv(
            "ZARINPAL_STARTPAY_URL",
            "https://sandbox.zarinpal.com/pg/StartPay",
        )
        .strip()
    )
else:
    if PAYMENT_DEFAULT_GATEWAY == "zarinpal":
        ZARINPAL_MERCHANT_ID = _required_env("ZARINPAL_MERCHANT_ID")
        ZARINPAL_CALLBACK_URL = _required_env("ZARINPAL_CALLBACK_URL")
        ZARINPAL_REQUEST_URL = _required_env("ZARINPAL_REQUEST_URL")
        ZARINPAL_VERIFY_URL = _required_env("ZARINPAL_VERIFY_URL")
        ZARINPAL_STARTPAY_URL = _required_env("ZARINPAL_STARTPAY_URL")

        sandbox_markers = ("sandbox.zarinpal.com",)
        for setting_name, setting_value in (
            ("ZARINPAL_REQUEST_URL", ZARINPAL_REQUEST_URL),
            ("ZARINPAL_VERIFY_URL", ZARINPAL_VERIFY_URL),
            ("ZARINPAL_STARTPAY_URL", ZARINPAL_STARTPAY_URL),
        ):
            if any(
                marker in setting_value.lower()
                for marker in sandbox_markers
            ):
                raise RuntimeError(
                    f"{setting_name} must not point to a ZarinPal sandbox URL "
                    "when DJANGO_DEBUG=0."
                )
    else:
        ZARINPAL_REQUEST_URL = os.getenv("ZARINPAL_REQUEST_URL", "").strip()
        ZARINPAL_VERIFY_URL = os.getenv("ZARINPAL_VERIFY_URL", "").strip()
        ZARINPAL_STARTPAY_URL = os.getenv("ZARINPAL_STARTPAY_URL", "").strip()
