# Generated by Django 6.0.6 on 2026-07-12 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='آدرس سئو (Slug)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / قابل نمایش')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='دسته\u200cبندی مادر')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام فارسی')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام انگلیسی محصول')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='برند')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات کوتاه')),
                ('review', models.TextField(blank=True, verbose_name='نقد و بررسی تخصصی')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قیمت فعلی (تومان)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت قبلی / بدون تخفیف (تومان)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی در انبار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / قابل نمایش')),
                ('is_available_status', models.BooleanField(default=True, verbose_name='موجود بودن')),
                ('highlights', models.TextField(blank=True, verbose_name='ویژگی\u200cهای کلیدی (هر ویژگی را در یک خط جدید بنویسید)')),
                ('guarantee', models.CharField(default='۱۸ ماه گارانتی شرکتی', max_length=200, verbose_name='گارانتی')),
                ('delivery_info', models.CharField(default='ارسال سریع به سراسر کشور', max_length=200, verbose_name='اطلاعات ارسال')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/%Y/%m/%d', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'گالری تصاویر محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان ویژگی (مثلاً وزن)')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصه فنی محصول',
                'verbose_name_plural': 'مشخصات فنی محصول',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='catalog_pro_id_a44864_idx'),
        ),
    ]
