# Generated by Django 6.0.6 on 2026-07-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_UniqueConstrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تأیید شده'),
        ),
    ]
