# Generated by Django 6.0.6 on 2026-07-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0002_alter_product_highlights_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('saved', 'ذخیره شده')], default='active', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['status'], name='cart_cartit_status_401e96_idx'),
        ),
    ]
