# Generated by Django 6.0.6 on 2026-09-13 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitems'),
        ('catalog', '0006_updatepayments'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_product_per_cart',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cart_cartit_cart_id_4bd8c3_idx',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.productvariant', verbose_name='تنوع محصول'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product', 'variant'], name='cart_cartit_cart_id_bddf3b_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['variant'], name='cart_cartit_variant_f80a7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('cart', 'product'), name='unique_product_without_variant_per_cart'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('cart', 'product', 'variant'), name='unique_product_variant_per_cart'),
        ),
    ]
