# Generated by Django 6.0.6 on 2026-07-26 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_cartitems'),
        ('catalog', '0006_updatepayments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار ثبت'), ('placed', 'ثبت شده'), ('paid', 'پرداخت شده'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='جمع مبلغ کالاها')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ تخفیف')),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='هزینه ارسال')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ نهایی')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('customer_note', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('stock_reduced', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.cart', verbose_name='سبد مرجع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderAddressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='نام گیرنده')),
                ('recipient_mobile', models.CharField(max_length=15, verbose_name='موبایل گیرنده')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('province', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('address_line', models.CharField(max_length=255, verbose_name='آدرس دقیق')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_snapshot', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'اسنپ\u200cشات آدرس سفارش',
                'verbose_name_plural': 'اسنپ\u200cشات\u200cهای آدرس سفارش',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.BigIntegerField(blank=True, null=True, verbose_name='شناسه واریانت')),
                ('product_name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('variant_name', models.CharField(blank=True, max_length=255, verbose_name='نام واریانت')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت واحد')),
                ('subtotal_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='جمع قیمت سطر')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('refunded', 'مرجوع شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('gateway_name', models.CharField(blank=True, max_length=50, verbose_name='نام درگاه پرداخت')),
                ('transaction_code', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='کد تراکنش درگاه')),
                ('reference_code', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='کد رهگیری پرداخت')),
                ('gateway_response', models.TextField(blank=True, verbose_name='پاسخ درگاه')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد تراکنش')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی تراکنش')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created'], name='orders_orde_created_51311f_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['variant_id'], name='orders_orde_variant_164791_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='orders_paym_status_83f434_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_name'], name='orders_paym_gateway_851c2c_idx'),
        ),
    ]
