# Generated by Django 6.0.6 on 2026-07-30 13:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='مبلغ نهایی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='هزینه ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='جمع مبلغ کالاها'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ پرداخت'),
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام روش ارسال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='هزینه ارسال (تومان)')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل مبلغ سفارش برای ارسال رایگان (تومان)')),
                ('estimated_delivery_days', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='زمان تخمینی تحویل (روز)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'روش ارسال',
                'verbose_name_plural': 'روش\u200cهای ارسال',
                'ordering': ['cost', '-is_active'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='shipping_cost_gte_0'), models.CheckConstraint(condition=models.Q(('free_shipping_threshold__gte', 0), ('free_shipping_threshold__isnull', True), _connector='OR'), name='shipping_free_shipping_threshold_gte_0')],
            },
        ),
    ]
