# Generated by Django 6.0.6 on 2026-08-01 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ShippingMethodtoorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='cost',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='هزینه ارسال (تومان)'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='free_shipping_threshold',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل مبلغ سفارش برای ارسال رایگان (تومان)'),
        ),
    ]
